#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': 'leo-editor-snapshot-20130223',
 'build_date': '2013-02-23 02:53:53 -0600',
 'clean': None,
 'date': '2013-02-15 11:16:57 -0600',
 'revision_id': 'edreamleo@gmail.com-20130215171657-fb5cys1cixvl9ss3',
 'revno': '5603'}

revisions = {}

file_revisions = {}


if __name__ == '__main__':
    print('revision: %(revno)s' % version_info)
    print('nick: %(branch_nick)s' % version_info)
    print('revision id: %(revision_id)s' % version_info)
